#!/bin/bash

conn=$(ping -w 2 github.com);

if [ -d "$HOME/.cmd" ] && [ -n "$conn" ]; then
    if [ "$LANGUAGE" = "pt_BR" ]; then echo "Deletando Todas configurações..."; else echo "Deleting all settings..."; fi
    gh repo delete .cmd --confirm
    rm -rf "$HOME"/.cmd
    if [ "$LANGUAGE" = "pt_BR" ]; then echo "Tudo OK! Reinicie a aplicação, saindo..."; else echo "OK! Restart! Exitting...";fi
elif [ -z "$conn" ];then
    if [ "$LANGUAGE" = "pt_BR" ]; then echo "Conexão com a internet falhou! "; else echo "Networking Failed! "; fi
else 
    if [ "$LANGUAGE" = "pt_BR" ]; then echo "Configurações inesxistentes!"; else echo "Settings not found!"; fi
fi

exit